<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <Version>2.0.0</Version>
    <Product>Nexus Shell</Product>
    <Company>Nexus Shell</Company>
    <NeutralLanguage>ru-RU</NeutralLanguage>
  </PropertyGroup>
</Project>
