<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <WindowsSdkPackageVersion>10.0.22621.38</WindowsSdkPackageVersion>
    <RootNamespace>Nexus.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <UseWinUI>true</UseWinUI>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ApplicationIcon>Assets\Nexus.ico</ApplicationIcon>
    <Version>0.8.0</Version>
    <AssemblyVersion>0.8.0.0</AssemblyVersion>
    <FileVersion>0.8.0.0</FileVersion>
    <InformationalVersion>0.8.0</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexus.Core\Nexus.Core.csproj" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.240923002" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1742" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools.MSIX" Version="1.6.20250507.1" PrivateAssets="all" />
    <Content Include="Assets\Nexus.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\Nexus.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <Target Name="CopyCompiledXamlToPublishDirectory" AfterTargets="Publish">
    <ItemGroup>
      <NexusCompiledXaml Include="$(TargetDir)App.xbf" />
      <NexusCompiledXaml Include="$(TargetDir)MainWindow.xbf" />
      <NexusCompiledXaml Include="$(TargetDir)Nexus.App.pri" />
    </ItemGroup>

    <Copy
      SourceFiles="@(NexusCompiledXaml)"
      DestinationFolder="$(PublishDir)"
      SkipUnchangedFiles="true" />
  </Target>
</Project>
